### ISSUE TITLE
Unable to run the code

### ISSUE THREAD

**Issue by KorneliaBastin** [FabianGroeger96/cnn-number-detection#16]
Hi, 

I am trying to run the code using already train models on one of the available images. I basically just want to test how it works. 

I am in cnn-number-detection folder and I run python3 Tester/test_model.py -h and get the following error:

from Tester.tester import Tester
ModuleNotFoundError: No module named 'Tester'

I am not sure what and how to change, the dependencies look ok so I have no idea what is wrong. Could you please help?

**Comment by FabianGroeger96** [comment]
The imports in the project are done by importing them as modules. Thus you have to start all scripts with the respective flag `-m` from python as follows: `python3 -m Tester.test_model -h`

**Comment by KorneliaBastin** [comment]
Hi, 

Thank you for your reply, it did solve the initial issue. 

Now I get another error when I try to run the code.

I run:

python3 -m Tester.test_model

and I get this error:

2022-01-13 14:53:43,006 - Model - INFO - Creating model: CNN-gnet-deep-Tester
/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)
2022-01-13 14:53:43.111379: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/cnn-number-detection/Tester/test_model.py", line 57, in <module>
    main()
  File "/content/cnn-number-detection/Tester/test_model.py", line 33, in main
    tester = Tester(model_obj, args.model_path)
  File "/content/cnn-number-detection/Tester/tester.py", line 15, in __init__
    model_obj.create_model(weights_path=model_path)
  File "/content/cnn-number-detection/Trainer/Models/model_gnet_deep.py", line 46, in create_model
    self.model.load_weights(weights_path)
  File "/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.7/dist-packages/h5py/_hl/files.py", line 427, in __init__
    swmr=swmr)
  File "/usr/local/lib/python3.7/dist-packages/h5py/_hl/files.py", line 190, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 96, in h5py.h5f.open
OSError: Unable to open file (file signature not found)

**Comment by KorneliaBastin** [comment]
Thank you! 

I seem to have the code working now. But I encounter few more issues. When I run the code on picture without numbers I get:

Total params: 57,482
Trainable params: 57,482
Non-trainable params: 0
_________________________________________________________________
2022-01-13 15:35:07,428 - Tester - INFO - [Prediction] type: info, category: -1 (100.00%)
: cannot connect to X server 

Which seems fine, category is -1 so no digit detected, but when I run it on the picture with digits I get:

Total params: 57,482
Trainable params: 57,482
Non-trainable params: 0
_________________________________________________________________

and thats it! What is the detected digit? There is no prediction displayed anywhere....


Also another thing is I tried to run the code on my image and I get the error message as below:

Total params: 57,482
Trainable params: 57,482
Non-trainable params: 0
_________________________________________________________________
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/cnn-number-detection/Tester/test_model.py", line 57, in <module>
    main()
  File "/content/cnn-number-detection/Tester/test_model.py", line 37, in main
    tester.test_model_with_image(args.test_image)
  File "/content/cnn-number-detection/Tester/tester.py", line 25, in test_model_with_image
    regions_of_interest = self.isolator.get_regions_of_interest(image_array)
  File "/content/cnn-number-detection/Isolator/isolator.py", line 25, in get_regions_of_interest
    cropped_images = self.__crop(image)
  File "/content/cnn-number-detection/Isolator/isolator.py", line 78, in __crop
    info_start = self.CONSTANTS.CROP_INFO_HEIGHT_START
AttributeError: 'NoneType' object has no attribute 'CROP_INFO_HEIGHT_START'


Not sure how I can give my image those attributes

Could you please advice? 

Thanks,
Kornelia
